### ISSUE TITLE
Bug 🐞: About page crashes on navigation

### ISSUE THREAD

**Issue by viveknigam3003** [louremipsum/scheduling#2]
The about page is crashing when navigating to it with an undefined property error

<img width="1440" alt="Screen Shot 2022-10-16 at 10 15 55 PM" src="https://user-images.githubusercontent.com/30192068/196047620-ab275172-cc7d-4a34-b17e-598be8b605ba.png">

**Comment by louremipsum** [comment]
yes!

**Comment by viveknigam3003** [comment]
Please assign this issue to me
